-- https://school.programmers.co.kr/learn/courses/30/lessons/131116

WITH VT AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT FP.CATEGORY, VT.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN VT ON FP.CATEGORY = VT.CATEGORY
WHERE FP.PRICE = VT.MAX_PRICE
ORDER BY VT.MAX_PRICE DESC