-- https://school.programmers.co.kr/learn/courses/30/lessons/151139

WITH VT AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
)
SELECT MONTH(START_DATE) AS MONTH, RH.CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
LEFT JOIN VT ON RH.CAR_ID = VT.CAR_ID
WHERE VT.CAR_ID IS NOT NULL AND YEAR(START_DATE) = 2022 AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
GROUP BY MONTH, RH.CAR_ID
ORDER BY MONTH, RH.CAR_ID DESC