-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

WITH VT AS (
    SELECT * FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT UI.USER_ID) / (SELECT COUNT(*) FROM VT), 1) AS PUCHASED_RATIO
FROM USER_INFO AS UI
JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
WHERE YEAR(UI.JOINED) = 2021
GROUP BY 1, 2
ORDER BY 1, 2