-- https://school.programmers.co.kr/learn/courses/30/lessons/131123

WITH VT AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO AS RI
JOIN VT ON RI.FOOD_TYPE = VT.FOOD_TYPE
WHERE RI.FAVORITES = VT.FAVORITES
ORDER BY RI.FOOD_TYPE DESC