-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

WITH H AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-11-30'
    GROUP BY 1
)

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * (1 - P.DISCOUNT_RATE * 0.01) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
LEFT JOIN H ON C.CAR_ID = H.CAR_ID
WHERE H.CAR_ID IS NULL
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY 3 DESC, 1