-- https://school.programmers.co.kr/learn/courses/30/lessons/157340

WITH VT AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)

SELECT RH.CAR_ID, IF(VT.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
LEFT JOIN VT ON RH.CAR_ID = VT.CAR_ID
GROUP BY RH.CAR_ID
ORDER BY RH.CAR_ID DESC