-- https://school.programmers.co.kr/learn/courses/30/lessons/276036

WITH FE AS (
    SELECT SUM(CODE) AS CF
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT 
    CASE
        WHEN (SKILL_CODE & (SELECT CF FROM FE)) AND (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
        WHEN SKILL_CODE & (SELECT CF FROM FE) THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID