-- https://school.programmers.co.kr/learn/courses/30/lessons/298519

SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY 3
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY 3