-- https://school.programmers.co.kr/learn/courses/30/lessons/284529

SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, ROUND(AVG(HE.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT AS HD
JOIN HR_EMPLOYEES AS HE ON HD.DEPT_ID = HE.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC