-- https://school.programmers.co.kr/learn/courses/30/lessons/293261

WITH VT AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT DISTINCT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
JOIN VT ON FI.FISH_TYPE = VT.FISH_TYPE
WHERE FI.LENGTH = VT.LENGTH
ORDER BY FI.ID