# https://school.programmers.co.kr/learn/courses/30/lessons/59411

SELECT AI.ANIMAL_ID, AO.NAME
FROM ANIMAL_INS AS AI
JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(SECOND, AI.DATETIME, AO.DATETIME) DESC
LIMIT 2